services:
  - type: web
    name: whereismybus-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build && npm run db:seed
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
